<template>
  <q-page padding>
    <div class="q-pa-md">
      <h5 class="q-my-none q-mb-md">{{ $t('nav.billing') }}</h5>
      <div class="row q-col-gutter-md q-mb-lg"><div class="col-12 col-sm-6 col-md-3"><q-card class="stat-card"><q-card-section><div class="stat-value text-positive">€ {{ stats.totalRevenue.toLocaleString() }}</div><div class="stat-label">Total Revenue</div></q-card-section></q-card></div><div class="col-12 col-sm-6 col-md-3"><q-card class="stat-card"><q-card-section><div class="stat-value text-warning">€ {{ stats.pending.toLocaleString() }}</div><div class="stat-label">Pending</div></q-card-section></q-card></div><div class="col-12 col-sm-6 col-md-3"><q-card class="stat-card"><q-card-section><div class="stat-value text-negative">€ {{ stats.overdue.toLocaleString() }}</div><div class="stat-label">Overdue</div></q-card-section></q-card></div><div class="col-12 col-sm-6 col-md-3"><q-card class="stat-card"><q-card-section><div class="stat-value text-info">{{ stats.invoices }}</div><div class="stat-label">Total Invoices</div></q-card-section></q-card></div></div>
      <q-card class="q-mb-md"><q-card-section><div class="row items-center q-mb-md"><div class="col"><div class="text-h6">Invoices</div></div><div class="col-auto"><q-btn color="primary" icon="add" label="Generate Invoice" @click="showInvoiceDialog = true" no-caps unelevated /></div></div><q-table :rows="invoices" :columns="columns" row-key="id" :loading="loading" flat bordered><template v-slot:body-cell-status="props"><q-td :props="props"><q-badge :color="getStatusColor(props.row.status)" :label="props.row.status" /></q-td></template><template v-slot:body-cell-amount="props"><q-td :props="props">€ {{ props.row.amount.toFixed(2) }}</q-td></template><template v-slot:body-cell-actions="props"><q-td :props="props"><q-btn flat round dense icon="visibility" color="primary" @click="viewInvoice(props.row.id)" /><q-btn flat round dense icon="download" color="secondary" @click="downloadInvoice(props.row.id)" /></q-td></template></q-table></q-card-section></q-card>
      <q-dialog v-model="showInvoiceDialog" persistent><q-card style="min-width: 600px"><q-card-section><div class="text-h6">Generate Invoice</div></q-card-section><q-card-section><q-form @submit="generateInvoice" class="q-gutter-md"><q-select v-model="newInvoice.complexId" :options="complexes" option-value="id" option-label="name" label="Complex *" outlined emit-value map-options :rules="[val => !!val || 'Required']" /><q-select v-model="newInvoice.unitId" :options="units" option-value="id" option-label="unitNumber" label="Unit *" outlined emit-value map-options :rules="[val => !!val || 'Required']" /><q-input v-model="newInvoice.period" label="Billing Period *" outlined type="month" :rules="[val => !!val || 'Required']" /><q-input v-model.number="newInvoice.amount" type="number" label="Amount (€) *" outlined :rules="[val => val > 0 || 'Required']" /><q-input v-model="newInvoice.dueDate" label="Due Date *" outlined type="date" :rules="[val => !!val || 'Required']" /><q-input v-model="newInvoice.description" label="Description" outlined type="textarea" rows="2" /><div class="row q-gutter-md justify-end"><q-btn flat label="Cancel" color="grey" v-close-popup /><q-btn type="submit" label="Generate" color="primary" :loading="generating" /></div></q-form></q-card-section></q-card></q-dialog>
    </div>
  </q-page>
</template>
<script>
import { defineComponent, ref, onMounted, computed } from 'vue'; import { useRouter } from 'vue-router'; import { useI18n } from 'vue-i18n'; import { useQuasar } from 'quasar'; import { billingAPI, complexesAPI, unitsAPI } from '../../api';
export default defineComponent({ name: 'BillingOverviewPage', setup() { const router = useRouter(); const { t } = useI18n(); const $q = useQuasar(); const loading = ref(false), generating = ref(false), invoices = ref([]), complexes = ref([]), units = ref([]), showInvoiceDialog = ref(false); const stats = ref({ totalRevenue: 125000, pending: 23500, overdue: 5600, invoices: 342 }); const newInvoice = ref({ complexId: null, unitId: null, period: '', amount: null, dueDate: '', description: '' }); const columns = computed(() => [{ name: 'invoiceNumber', label: 'Invoice #', field: 'invoiceNumber', align: 'left', sortable: true }, { name: 'unit', label: 'Unit', field: row => row.unit?.unitNumber, align: 'left' }, { name: 'period', label: 'Period', field: 'period', align: 'left' }, { name: 'amount', label: 'Amount', field: 'amount', align: 'right', sortable: true }, { name: 'dueDate', label: 'Due Date', field: 'dueDate', align: 'left', format: val => new Date(val).toLocaleDateString() }, { name: 'status', label: 'Status', field: 'status', align: 'center', sortable: true }, { name: 'actions', label: 'Actions', field: 'actions', align: 'center' }]); const getStatusColor = (status) => ({ paid: 'positive', pending: 'warning', overdue: 'negative', cancelled: 'grey' }[status]); const fetchInvoices = async () => { loading.value = true; try { const response = await billingAPI.getAll(); invoices.value = response.data.data || []; } catch (error) { $q.notify({ message: error.message, color: 'negative', icon: 'error' }); } finally { loading.value = false; } }; const fetchComplexes = async () => { try { const response = await complexesAPI.getAll({ limit: 100 }); complexes.value = response.data.data || []; } catch (error) { console.error('Failed', error); } }; const viewInvoice = (id) => { router.push(`/billing/${id}`); }; const downloadInvoice = (id) => { $q.notify({ message: 'Downloading invoice...', color: 'info' }); }; const generateInvoice = async () => { generating.value = true; try { await billingAPI.create(newInvoice.value); $q.notify({ message: 'Invoice generated successfully', color: 'positive', icon: 'check' }); showInvoiceDialog.value = false; newInvoice.value = { complexId: null, unitId: null, period: '', amount: null, dueDate: '', description: '' }; await fetchInvoices(); } catch (error) { $q.notify({ message: error.message, color: 'negative', icon: 'error' }); } finally { generating.value = false; } }; onMounted(() => { fetchInvoices(); fetchComplexes(); }); return { loading, generating, invoices, complexes, units, stats, columns, showInvoiceDialog, newInvoice, getStatusColor, viewInvoice, downloadInvoice, generateInvoice }; } });
</script>
