<template>
  <q-page padding>
    <div class="q-pa-md" style="max-width: 900px; margin: 0 auto;">
      <div class="row items-center q-mb-md"><div class="col"><h5 class="q-my-none">Invoice #{{ invoice?.invoiceNumber }}</h5><q-badge :color="getStatusColor(invoice?.status)" :label="invoice?.status" class="q-ml-sm" /></div><div class="col-auto q-gutter-sm"><q-btn flat icon="arrow_back" label="Back" @click="$router.back()" no-caps /><q-btn color="secondary" icon="download" label="Download PDF" @click="downloadPDF" no-caps unelevated /><q-btn v-if="invoice?.status === 'pending'" color="primary" icon="payment" label="Pay Now" @click="showPayDialog = true" no-caps unelevated /></div></div>
      <q-inner-loading :showing="loading" />
      <div v-if="!loading && invoice">
        <q-card class="q-mb-md invoice-card"><q-card-section class="bg-grey-1"><div class="row"><div class="col-6"><div class="text-h6">ServAI</div><div class="text-caption">AI Property Management</div></div><div class="col-6 text-right"><div class="text-h6">INVOICE</div><div class="text-caption">#{{ invoice.invoiceNumber }}</div></div></div></q-card-section><q-separator /><q-card-section><div class="row q-col-gutter-md q-mb-md"><div class="col-6"><div class="text-subtitle2 q-mb-xs">Billed To:</div><div><strong>{{ invoice.unit?.complex?.name }}</strong></div><div>Unit: {{ invoice.unit?.unitNumber }}</div></div><div class="col-6 text-right"><div class="text-subtitle2 q-mb-xs">Invoice Details:</div><div>Date: {{ formatDate(invoice.createdAt) }}</div><div>Due Date: {{ formatDate(invoice.dueDate) }}</div><div>Period: {{ invoice.period }}</div></div></div><q-separator /><div class="q-my-md"><div class="text-subtitle2 q-mb-md">Items:</div><q-markup-table flat bordered><thead><tr><th class="text-left">Description</th><th class="text-right">Amount</th></tr></thead><tbody><tr><td>{{ invoice.description || 'Monthly Service Fee' }}</td><td class="text-right">€ {{ invoice.amount.toFixed(2) }}</td></tr></tbody></q-markup-table></div><q-separator /><div class="row q-mt-md"><div class="col"></div><div class="col-auto" style="min-width: 250px;"><div class="row justify-between q-mb-sm"><div class="text-subtitle2">Subtotal:</div><div>€ {{ invoice.amount.toFixed(2) }}</div></div><div class="row justify-between q-mb-sm"><div class="text-subtitle2">Tax (0%):</div><div>€ 0.00</div></div><q-separator class="q-my-sm" /><div class="row justify-between"><div class="text-h6">Total:</div><div class="text-h6 text-primary">€ {{ invoice.amount.toFixed(2) }}</div></div></div></div></q-card-section></q-card>
        <q-card v-if="invoice.payments?.length > 0"><q-card-section><div class="text-h6 q-mb-md">Payment History</div><q-list separator><q-item v-for="payment in invoice.payments" :key="payment.id"><q-item-section><q-item-label>{{ formatDate(payment.paidAt) }}</q-item-label><q-item-label caption>{{ payment.method }}</q-item-label></q-item-section><q-item-section side><div class="text-positive">€ {{ payment.amount.toFixed(2) }}</div></q-item-section></q-item></q-list></q-card-section></q-card>
      </div>
      <q-dialog v-model="showPayDialog" persistent><q-card style="min-width: 400px"><q-card-section><div class="text-h6">Pay Invoice</div></q-card-section><q-card-section><div class="text-h4 text-primary q-mb-md">€ {{ invoice?.amount.toFixed(2) }}</div><q-select v-model="paymentMethod" :options="['Credit Card', 'Bank Transfer', 'Cash']" label="Payment Method" outlined /></q-card-section><q-card-actions align="right"><q-btn flat label="Cancel" color="grey" v-close-popup /><q-btn label="Pay Now" color="primary" @click="processPayment" :loading="paying" no-caps unelevated /></q-card-actions></q-card></q-dialog>
    </div>
  </q-page>
</template>
<script>
import { defineComponent, ref, onMounted, computed } from 'vue'; import { useRoute, useRouter } from 'vue-router'; import { useQuasar } from 'quasar'; import { billingAPI } from '../../api';
export default defineComponent({ name: 'ViewInvoicePage', setup() { const route = useRoute(); const router = useRouter(); const $q = useQuasar(); const loading = ref(false), paying = ref(false), invoice = ref(null), showPayDialog = ref(false), paymentMethod = ref('Credit Card'); const invoiceId = computed(() => route.params.id); const getStatusColor = (status) => ({ paid: 'positive', pending: 'warning', overdue: 'negative', cancelled: 'grey' }[status]); const formatDate = (date) => new Date(date).toLocaleDateString(); const fetchInvoice = async () => { loading.value = true; try { const response = await billingAPI.getById(invoiceId.value); invoice.value = response.data; } catch (error) { $q.notify({ message: error.message, color: 'negative', icon: 'error' }); } finally { loading.value = false; } }; const downloadPDF = () => { $q.notify({ message: 'Downloading PDF...', color: 'info' }); }; const processPayment = async () => { paying.value = true; try { await billingAPI.payInvoice(invoiceId.value, { method: paymentMethod.value }); $q.notify({ message: 'Payment processed successfully', color: 'positive', icon: 'check' }); showPayDialog.value = false; await fetchInvoice(); } catch (error) { $q.notify({ message: error.message, color: 'negative', icon: 'error' }); } finally { paying.value = false; } }; onMounted(() => { fetchInvoice(); }); return { loading, paying, invoice, showPayDialog, paymentMethod, getStatusColor, formatDate, downloadPDF, processPayment }; } });
</script>
<style lang="scss" scoped>
.invoice-card { box-shadow: 0 2px 12px rgba(0,0,0,0.1); }
</style>
