<template>
  <q-page padding>
    <div class="q-pa-md">
      <div class="row items-center q-mb-md"><div class="col"><h5 class="q-my-none">{{ $t('nav.polls') }}</h5></div><div class="col-auto"><q-btn color="primary" icon="add" label="Create Poll" @click="showCreateDialog = true" no-caps unelevated /></div></div>
      <div class="row q-col-gutter-md"><div v-for="poll in polls" :key="poll.id" class="col-12 col-md-6"><q-card class="poll-card" flat bordered><q-card-section><div class="row items-center"><div class="col"><div class="text-h6">{{ poll.title }}</div><div class="text-caption text-grey-7">{{ poll.description }}</div></div><div class="col-auto"><q-badge :color="poll.status === 'active' ? 'positive' : 'grey'" :label="poll.status" /></div></div></q-card-section><q-separator /><q-card-section><div class="text-subtitle2 q-mb-sm">Options:</div><div v-for="option in poll.options" :key="option.id" class="q-mb-sm"><div class="row items-center"><div class="col-auto" style="width: 60px"><q-btn flat dense :label="option.votes" color="primary" size="sm" /></div><div class="col"><q-linear-progress :value="option.votes / poll.totalVotes" color="primary" class="q-mr-sm" /><div class="text-caption">{{ option.text }} ({{ ((option.votes / poll.totalVotes) * 100).toFixed(1) }}%)</div></div></div></div></q-card-section><q-separator /><q-card-actions align="right"><div class="text-caption text-grey-7">{{ poll.totalVotes }} votes</div><q-space /><q-btn flat label="View" color="primary" @click="viewPoll(poll.id)" /><q-btn flat label="Edit" color="secondary" @click="editPoll(poll)" v-if="poll.status === 'draft'" /></q-card-actions></q-card></div></div>
      <q-dialog v-model="showCreateDialog" persistent><q-card style="min-width: 600px"><q-card-section><div class="text-h6">Create Poll</div></q-card-section><q-card-section><q-form @submit="createPoll" class="q-gutter-md"><q-input v-model="newPoll.title" label="Title *" outlined :rules="[val => !!val || 'Required']" /><q-input v-model="newPoll.description" label="Description" outlined type="textarea" rows="2" /><q-select v-model="newPoll.complexId" :options="complexes" option-value="id" option-label="name" label="Complex *" outlined emit-value map-options :rules="[val => !!val || 'Required']" /><div class="text-subtitle2 q-mt-md">Options:</div><div v-for="(option, index) in newPoll.options" :key="index" class="row q-col-gutter-sm q-mb-sm"><div class="col"><q-input v-model="newPoll.options[index]" :label="`Option ${index + 1} *`" outlined dense :rules="[val => !!val || 'Required']" /></div><div class="col-auto"><q-btn flat round dense icon="delete" color="negative" @click="removeOption(index)" v-if="newPoll.options.length > 2" /></div></div><q-btn flat label="Add Option" icon="add" color="primary" @click="addOption" size="sm" /><q-input v-model="newPoll.endDate" label="End Date" outlined type="date" class="q-mt-md" /><div class="row q-gutter-md justify-end q-mt-md"><q-btn flat label="Cancel" color="grey" v-close-popup /><q-btn type="submit" label="Create" color="primary" :loading="creating" /></div></q-form></q-card-section></q-card></q-dialog>
    </div>
  </q-page>
</template>
<script>
import { defineComponent, ref, onMounted } from 'vue'; import { useRouter } from 'vue-router'; import { useQuasar } from 'quasar'; import { pollsAPI, complexesAPI } from '../../api';
export default defineComponent({ name: 'PollsListPage', setup() { const router = useRouter(); const $q = useQuasar(); const creating = ref(false), polls = ref([]), complexes = ref([]), showCreateDialog = ref(false); const newPoll = ref({ title: '', description: '', complexId: null, options: ['', ''], endDate: '' }); const fetchPolls = async () => { try { const response = await pollsAPI.getAll(); polls.value = response.data.data || []; } catch (error) { $q.notify({ message: error.message, color: 'negative', icon: 'error' }); } }; const fetchComplexes = async () => { try { const response = await complexesAPI.getAll({ limit: 100 }); complexes.value = response.data.data || []; } catch (error) { console.error('Failed', error); } }; const addOption = () => { newPoll.value.options.push(''); }; const removeOption = (index) => { newPoll.value.options.splice(index, 1); }; const viewPoll = (id) => { router.push(`/polls/${id}`); }; const editPoll = (poll) => { console.log('Edit', poll); }; const createPoll = async () => { creating.value = true; try { await pollsAPI.create(newPoll.value); $q.notify({ message: 'Poll created successfully', color: 'positive', icon: 'check' }); showCreateDialog.value = false; newPoll.value = { title: '', description: '', complexId: null, options: ['', ''], endDate: '' }; await fetchPolls(); } catch (error) { $q.notify({ message: error.message, color: 'negative', icon: 'error' }); } finally { creating.value = false; } }; onMounted(() => { fetchPolls(); fetchComplexes(); }); return { creating, polls, complexes, showCreateDialog, newPoll, addOption, removeOption, viewPoll, editPoll, createPoll }; } });
</script>
<style lang="scss" scoped>
.poll-card { transition: transform 0.2s; &:hover { transform: translateY(-2px); box-shadow: 0 4px 8px rgba(0,0,0,0.1); } }
</style>
