<template>
  <q-page padding>
    <div class="q-pa-md" style="max-width: 800px; margin: 0 auto;">
      <div class="row items-center q-mb-md"><div class="col"><h5 class="q-my-none">{{ poll?.title }}</h5><q-badge :color="poll?.status === 'active' ? 'positive' : 'grey'" :label="poll?.status" class="q-ml-sm" /></div><div class="col-auto"><q-btn flat icon="arrow_back" label="Back" @click="$router.back()" no-caps /></div></div>
      <q-inner-loading :showing="loading" />
      <div v-if="!loading && poll">
        <q-card class="q-mb-md"><q-card-section><p class="text-body1">{{ poll.description }}</p><div class="text-caption text-grey-7">Created: {{ formatDate(poll.createdAt) }}</div><div class="text-caption text-grey-7" v-if="poll.endDate">Ends: {{ formatDate(poll.endDate) }}</div></q-card-section></q-card>
        <q-card class="q-mb-md" v-if="!hasVoted && poll.status === 'active'"><q-card-section><div class="text-h6 q-mb-md">Cast Your Vote</div><q-option-group v-model="selectedOption" :options="pollOptions" color="primary" /><q-card-actions align="right" class="q-mt-md"><q-btn label="Submit Vote" color="primary" @click="submitVote" :loading="voting" :disable="!selectedOption" no-caps unelevated /></q-card-actions></q-card-section></q-card>
        <q-card><q-card-section><div class="text-h6 q-mb-md">Results ({{ poll.totalVotes }} votes)</div><div v-for="option in poll.options" :key="option.id" class="q-mb-md"><div class="row items-center q-mb-xs"><div class="col"><strong>{{ option.text }}</strong></div><div class="col-auto"><q-chip dense>{{ option.votes }} votes ({{ getPercentage(option.votes) }}%)</q-chip></div></div><q-linear-progress :value="option.votes / poll.totalVotes" :color="getColor(option.votes / poll.totalVotes)" size="12px" /></div></q-card-section></q-card>
      </div>
    </div>
  </q-page>
</template>
<script>
import { defineComponent, ref, onMounted, computed } from 'vue'; import { useRoute } from 'vue-router'; import { useQuasar } from 'quasar'; import { pollsAPI } from '../../api';
export default defineComponent({ name: 'ViewPollPage', setup() { const route = useRoute(); const $q = useQuasar(); const loading = ref(false), voting = ref(false), poll = ref(null), selectedOption = ref(null), hasVoted = ref(false); const pollId = computed(() => route.params.id); const pollOptions = computed(() => poll.value?.options?.map(opt => ({ label: opt.text, value: opt.id })) || []); const getPercentage = (votes) => poll.value?.totalVotes ? ((votes / poll.value.totalVotes) * 100).toFixed(1) : 0; const getColor = (ratio) => ratio > 0.5 ? 'positive' : ratio > 0.3 ? 'primary' : 'grey'; const formatDate = (date) => new Date(date).toLocaleString(); const fetchPoll = async () => { loading.value = true; try { const response = await pollsAPI.getById(pollId.value); poll.value = response.data; hasVoted.value = response.data.hasVoted || false; } catch (error) { $q.notify({ message: error.message, color: 'negative', icon: 'error' }); } finally { loading.value = false; } }; const submitVote = async () => { voting.value = true; try { await pollsAPI.vote(pollId.value, selectedOption.value); $q.notify({ message: 'Vote submitted successfully', color: 'positive', icon: 'check' }); hasVoted.value = true; await fetchPoll(); } catch (error) { $q.notify({ message: error.message, color: 'negative', icon: 'error' }); } finally { voting.value = false; } }; onMounted(() => { fetchPoll(); }); return { loading, voting, poll, selectedOption, hasVoted, pollOptions, getPercentage, getColor, formatDate, submitVote }; } });
</script>
