<template>
  <q-page padding>
    <div class="q-pa-md" style="max-width: 800px; margin: 0 auto;">
      <h5 class="q-my-none q-mb-md">{{ $t('nav.profile') }}</h5>
      <q-card class="q-mb-md"><q-card-section><div class="row items-center"><div class="col-auto q-mr-md"><q-avatar size="80px" color="primary" text-color="white"><span class="text-h5">{{ initials }}</span></q-avatar></div><div class="col"><div class="text-h6">{{ profile.name }}</div><div class="text-caption text-grey-7">{{ profile.email }}</div><q-badge color="primary" :label="$t(`roles.${profile.role}`)" class="q-mt-xs" /></div><div class="col-auto"><q-btn flat label="Change Avatar" color="primary" size="sm" /></div></div></q-card-section></q-card>
      <q-tabs v-model="tab" align="left" class="q-mb-md"><q-tab name="personal" label="Personal Info" icon="person" /><q-tab name="security" label="Security" icon="lock" /><q-tab name="preferences" label="Preferences" icon="tune" /></q-tabs>
      <q-tab-panels v-model="tab" animated>
        <q-tab-panel name="personal"><q-card><q-card-section><div class="text-h6 q-mb-md">Personal Information</div><q-form @submit="saveProfile" class="q-gutter-md"><q-input v-model="profile.name" label="Full Name *" outlined :rules="[val => !!val || 'Required']" /><q-input v-model="profile.email" label="Email *" type="email" outlined readonly hint="Email cannot be changed" /><q-input v-model="profile.phone" label="Phone" outlined /><q-input v-model="profile.position" label="Position" outlined /><q-input v-model="profile.department" label="Department" outlined /><div class="row justify-end"><q-btn type="submit" label="Save Changes" color="primary" :loading="saving" no-caps unelevated /></div></q-form></q-card-section></q-card></q-tab-panel>
        <q-tab-panel name="security"><q-card><q-card-section><div class="text-h6 q-mb-md">Change Password</div><q-form @submit="changePassword" class="q-gutter-md"><q-input v-model="passwordForm.currentPassword" label="Current Password *" type="password" outlined :rules="[val => !!val || 'Required']" /><q-input v-model="passwordForm.newPassword" label="New Password *" type="password" outlined :rules="[val => !!val || 'Required', val => val.length >= 8 || 'Min 8 characters']" /><q-input v-model="passwordForm.confirmPassword" label="Confirm Password *" type="password" outlined :rules="[val => !!val || 'Required', val => val === passwordForm.newPassword || 'Passwords do not match']" /><div class="row justify-end"><q-btn type="submit" label="Change Password" color="primary" :loading="changingPassword" no-caps unelevated /></div></q-form></q-card-section></q-card><q-card class="q-mt-md"><q-card-section><div class="text-h6 q-mb-md">Two-Factor Authentication</div><q-list><q-item><q-item-section><q-item-label>Status</q-item-label><q-item-label caption>{{ twoFactorEnabled ? 'Enabled' : 'Disabled' }}</q-item-label></q-item-section><q-item-section side><q-btn flat :label="twoFactorEnabled ? 'Disable' : 'Enable'" :color="twoFactorEnabled ? 'negative' : 'positive'" @click="toggle2FA" /></q-item-section></q-item></q-list></q-card-section></q-card></q-tab-panel>
        <q-tab-panel name="preferences"><q-card><q-card-section><div class="text-h6 q-mb-md">Preferences</div><q-form @submit="savePreferences" class="q-gutter-md"><q-select v-model="preferences.language" :options="[{label: 'English', value: 'en'}, {label: 'Русский', value: 'ru'}, {label: 'Български', value: 'bg'}]" label="Language" outlined emit-value map-options /><q-select v-model="preferences.timezone" :options="['Europe/Moscow', 'Europe/Sofia', 'Europe/Berlin', 'UTC']" label="Timezone" outlined /><q-select v-model="preferences.dateFormat" :options="['DD/MM/YYYY', 'MM/DD/YYYY', 'YYYY-MM-DD']" label="Date Format" outlined /><q-toggle v-model="preferences.emailNotifications" label="Email Notifications" color="primary" /><q-toggle v-model="preferences.telegramNotifications" label="Telegram Notifications" color="primary" /><q-toggle v-model="preferences.darkMode" label="Dark Mode" color="primary" /><div class="row justify-end"><q-btn type="submit" label="Save Preferences" color="primary" :loading="saving" no-caps unelevated /></div></q-form></q-card-section></q-card></q-tab-panel>
      </q-tab-panels>
    </div>
  </q-page>
</template>
<script>
import { defineComponent, ref, onMounted, computed } from 'vue'; import { useQuasar } from 'quasar'; import { useAuthStore } from '../../stores'; import { profileAPI } from '../../api';
export default defineComponent({ name: 'ProfilePage', setup() { const $q = useQuasar(); const authStore = useAuthStore(); const saving = ref(false), changingPassword = ref(false), tab = ref('personal'), twoFactorEnabled = ref(false); const profile = ref({ name: '', email: '', phone: '', position: '', department: '', role: '' }); const passwordForm = ref({ currentPassword: '', newPassword: '', confirmPassword: '' }); const preferences = ref({ language: 'ru', timezone: 'Europe/Moscow', dateFormat: 'DD/MM/YYYY', emailNotifications: true, telegramNotifications: true, darkMode: false }); const initials = computed(() => { const names = profile.value.name.split(' '); return names.map(n => n[0]).join('').toUpperCase().slice(0, 2); }); const fetchProfile = async () => { try { const response = await profileAPI.get(); profile.value = response.data; preferences.value = response.data.preferences || preferences.value; twoFactorEnabled.value = response.data.twoFactorEnabled || false; } catch (error) { console.error('Failed to load profile', error); } }; const saveProfile = async () => { saving.value = true; try { await profileAPI.update(profile.value); $q.notify({ message: 'Profile updated successfully', color: 'positive', icon: 'check' }); } catch (error) { $q.notify({ message: error.message, color: 'negative', icon: 'error' }); } finally { saving.value = false; } }; const changePassword = async () => { changingPassword.value = true; try { await profileAPI.changePassword(passwordForm.value); $q.notify({ message: 'Password changed successfully', color: 'positive', icon: 'check' }); passwordForm.value = { currentPassword: '', newPassword: '', confirmPassword: '' }; } catch (error) { $q.notify({ message: error.message, color: 'negative', icon: 'error' }); } finally { changingPassword.value = false; } }; const savePreferences = async () => { saving.value = true; try { await profileAPI.updatePreferences(preferences.value); $q.notify({ message: 'Preferences saved successfully', color: 'positive', icon: 'check' }); } catch (error) { $q.notify({ message: error.message, color: 'negative', icon: 'error' }); } finally { saving.value = false; } }; const toggle2FA = async () => { try { if (twoFactorEnabled.value) { await profileAPI.disable2FA(); twoFactorEnabled.value = false; $q.notify({ message: '2FA disabled', color: 'positive', icon: 'check' }); } else { await profileAPI.enable2FA(); twoFactorEnabled.value = true; $q.notify({ message: '2FA enabled', color: 'positive', icon: 'check' }); } } catch (error) { $q.notify({ message: error.message, color: 'negative', icon: 'error' }); } }; onMounted(() => { profile.value = { ...authStore.user }; fetchProfile(); }); return { saving, changingPassword, tab, twoFactorEnabled, profile, passwordForm, preferences, initials, saveProfile, changePassword, savePreferences, toggle2FA }; } });
</script>
