<template>
  <q-page padding>
    <div class="q-pa-md">
      <div class="row items-center q-mb-md"><div class="col"><h5 class="q-my-none">{{ $t('nav.workers') }}</h5><p class="text-grey-7 q-mb-none">{{ $t('workers.subtitle') }}</p></div><div class="col-auto"><q-btn color="primary" icon="add" :label="$t('common.create')" @click="showCreateDialog = true" no-caps unelevated /></div></div>
      <q-card class="q-mb-md"><q-card-section><div class="row q-col-gutter-md"><div class="col-12 col-md-6"><q-input v-model="filters.search" :label="$t('common.search')" outlined dense clearable @update:model-value="onSearch"><template v-slot:prepend><q-icon name="search" /></template></q-input></div><div class="col-12 col-md-3"><q-select v-model="filters.position" :options="['Manager', 'Technician', 'Security', 'Cleaner']" :label="$t('workers.position')" outlined dense clearable @update:model-value="fetchWorkers" /></div><div class="col-12 col-md-3"><q-select v-model="filters.status" :options="statusOptions" :label="$t('common.status')" outlined dense emit-value map-options clearable @update:model-value="fetchWorkers" /></div></div></q-card-section></q-card>
      <q-card><q-table :rows="workers" :columns="columns" row-key="id" :loading="loading" :pagination="pagination" @request="onRequest" flat bordered><template v-slot:body-cell-actions="props"><q-td :props="props"><q-btn flat round dense icon="visibility" color="primary" @click="viewWorker(props.row.id)" /><q-btn flat round dense icon="edit" color="secondary" @click="editWorker(props.row)" /></q-td></template></q-table></q-card>
      <q-dialog v-model="showCreateDialog" persistent><q-card style="min-width: 600px"><q-card-section><div class="text-h6">{{ $t('common.create') }} Worker</div></q-card-section><q-card-section><q-form @submit="createWorker" class="q-gutter-md"><q-input v-model="newWorker.fullName" :label="$t('residents.fullName') + ' *'" outlined :rules="[val => !!val || $t('validation.required')]" /><q-input v-model="newWorker.email" :label="$t('common.email') + ' *'" type="email" outlined :rules="[val => !!val || $t('validation.required'), val => /.+@.+\..+/.test(val) || $t('validation.email')]" /><q-input v-model="newWorker.phone" :label="$t('common.phone')" outlined /><q-select v-model="newWorker.position" :options="['Manager', 'Technician', 'Security', 'Cleaner']" :label="$t('workers.position') + ' *'" outlined :rules="[val => !!val || $t('validation.required')]" /><q-input v-model="newWorker.hireDate" :label="$t('workers.hireDate')" outlined type="date" /><div class="row q-gutter-md justify-end"><q-btn flat :label="$t('common.cancel')" color="grey" v-close-popup /><q-btn type="submit" :label="$t('common.create')" color="primary" :loading="creating" /></div></q-form></q-card-section></q-card></q-dialog>
    </div>
  </q-page>
</template>
<script>
import { defineComponent, ref, onMounted, computed } from 'vue'; import { useRouter } from 'vue-router'; import { useI18n } from 'vue-i18n'; import { useQuasar } from 'quasar'; import { workersAPI } from '../../api';
export default defineComponent({ name: 'WorkersListPage', setup() { const router = useRouter(); const { t } = useI18n(); const $q = useQuasar(); const loading = ref(false), creating = ref(false), workers = ref([]), showCreateDialog = ref(false); const filters = ref({ search: '', position: null, status: null }), pagination = ref({ sortBy: 'fullName', descending: false, page: 1, rowsPerPage: 10, rowsNumber: 0 }); const newWorker = ref({ fullName: '', email: '', phone: '', position: '', hireDate: '' }); const columns = computed(() => [{ name: 'fullName', label: t('residents.fullName'), field: 'fullName', align: 'left', sortable: true }, { name: 'email', label: t('common.email'), field: 'email', align: 'left' }, { name: 'phone', label: t('common.phone'), field: 'phone', align: 'left' }, { name: 'position', label: t('workers.position'), field: 'position', align: 'left', sortable: true }, { name: 'actions', label: t('common.actions'), field: 'actions', align: 'center' }]); const statusOptions = computed(() => [{ label: t('common.active'), value: 'active' }, { label: t('common.inactive'), value: 'inactive' }]); const fetchWorkers = async (props = {}) => { loading.value = true; try { const { page, rowsPerPage, sortBy, descending } = props.pagination || pagination.value; const params = { page, limit: rowsPerPage, sortBy, order: descending ? 'desc' : 'asc', ...filters.value }; const response = await workersAPI.getAll(params); workers.value = response.data.data || []; pagination.value.page = response.data.page || 1; pagination.value.rowsPerPage = response.data.limit || 10; pagination.value.rowsNumber = response.data.total || 0; if (props.pagination) { pagination.value.sortBy = sortBy; pagination.value.descending = descending; } } catch (error) { $q.notify({ message: error.message || t('common.error'), color: 'negative', icon: 'error' }); } finally { loading.value = false; } }; let searchTimeout; const onSearch = () => { clearTimeout(searchTimeout); searchTimeout = setTimeout(() => { pagination.value.page = 1; fetchWorkers(); }, 500); }; const onRequest = (props) => { fetchWorkers(props); }; const viewWorker = (id) => { router.push(`/workers/${id}`); }; const editWorker = (worker) => { console.log('Edit', worker); }; const createWorker = async () => { creating.value = true; try { await workersAPI.create(newWorker.value); $q.notify({ message: t('workers.createSuccess'), color: 'positive', icon: 'check' }); showCreateDialog.value = false; newWorker.value = { fullName: '', email: '', phone: '', position: '', hireDate: '' }; await fetchWorkers(); } catch (error) { $q.notify({ message: error.message || t('common.error'), color: 'negative', icon: 'error' }); } finally { creating.value = false; } }; onMounted(() => { fetchWorkers(); }); return { loading, creating, workers, filters, pagination, columns, statusOptions, showCreateDialog, newWorker, onSearch, onRequest, viewWorker, editWorker, createWorker }; } });
</script>
