<template>
  <q-page padding>
    <div class="q-pa-md">
      <h5 class="q-my-none q-mb-md">{{ $t('nav.reports') }}</h5>
      <q-card class="q-mb-md"><q-card-section><div class="text-h6 q-mb-md">Generate Report</div><div class="row q-col-gutter-md"><div class="col-12 col-md-3"><q-select v-model="reportType" :options="reportTypes" label="Report Type" outlined dense /></div><div class="col-12 col-md-3"><q-input v-model="dateFrom" label="From" outlined dense type="date" /></div><div class="col-12 col-md-3"><q-input v-model="dateTo" label="To" outlined dense type="date" /></div><div class="col-12 col-md-3"><q-btn color="primary" icon="assessment" label="Generate" @click="generateReport" :loading="generating" class="full-width" no-caps unelevated /></div></div></q-card-section></q-card>
      <div class="row q-col-gutter-md q-mb-lg"><div class="col-12 col-sm-6 col-md-3"><q-card class="stat-card cursor-pointer" @click="reportType = 'financial'"><q-card-section class="text-center"><q-icon name="euro" size="48px" color="primary" /><div class="text-h6 q-mt-sm">Financial</div><div class="text-caption text-grey-7">Revenue & expenses</div></q-card-section></q-card></div><div class="col-12 col-sm-6 col-md-3"><q-card class="stat-card cursor-pointer" @click="reportType = 'occupancy'"><q-card-section class="text-center"><q-icon name="apartment" size="48px" color="secondary" /><div class="text-h6 q-mt-sm">Occupancy</div><div class="text-caption text-grey-7">Unit statistics</div></q-card-section></q-card></div><div class="col-12 col-sm-6 col-md-3"><q-card class="stat-card cursor-pointer" @click="reportType = 'maintenance'"><q-card-section class="text-center"><q-icon name="build" size="48px" color="warning" /><div class="text-h6 q-mt-sm">Maintenance</div><div class="text-caption text-grey-7">Tickets & repairs</div></q-card-section></q-card></div><div class="col-12 col-sm-6 col-md-3"><q-card class="stat-card cursor-pointer" @click="reportType = 'utilities'"><q-card-section class="text-center"><q-icon name="bolt" size="48px" color="info" /><div class="text-h6 q-mt-sm">Utilities</div><div class="text-caption text-grey-7">Meter readings</div></q-card-section></q-card></div></div>
      <q-card><q-card-section><div class="text-h6 q-mb-md">Recent Reports</div><q-table :rows="recentReports" :columns="columns" row-key="id" :loading="loading" flat bordered><template v-slot:body-cell-type="props"><q-td :props="props"><q-badge color="primary" :label="props.row.type" /></q-td></template><template v-slot:body-cell-actions="props"><q-td :props="props"><q-btn flat round dense icon="visibility" color="primary" @click="viewReport(props.row.id)" /><q-btn flat round dense icon="download" color="secondary" @click="downloadReport(props.row)" /></q-td></template></q-table></q-card-section></q-card>
    </div>
  </q-page>
</template>
<script>
import { defineComponent, ref, onMounted, computed } from 'vue'; import { useQuasar } from 'quasar'; import { reportsAPI } from '../../api';
export default defineComponent({ name: 'ReportsOverviewPage', setup() { const $q = useQuasar(); const loading = ref(false), generating = ref(false), recentReports = ref([]); const reportType = ref('financial'), dateFrom = ref(''), dateTo = ref(''); const reportTypes = ['financial', 'occupancy', 'maintenance', 'utilities', 'tenant', 'payment']; const columns = computed(() => [{ name: 'type', label: 'Type', field: 'type', align: 'left' }, { name: 'period', label: 'Period', field: 'period', align: 'left' }, { name: 'generatedAt', label: 'Generated', field: 'generatedAt', align: 'left', format: val => new Date(val).toLocaleString() }, { name: 'generatedBy', label: 'By', field: 'generatedBy', align: 'left' }, { name: 'actions', label: 'Actions', field: 'actions', align: 'center' }]); const fetchRecentReports = async () => { loading.value = true; try { const response = await reportsAPI.getAll(); recentReports.value = response.data.data || []; } catch (error) { $q.notify({ message: error.message, color: 'negative', icon: 'error' }); } finally { loading.value = false; } }; const generateReport = async () => { generating.value = true; try { const response = await reportsAPI.generate({ type: reportType.value, dateFrom: dateFrom.value, dateTo: dateTo.value }); $q.notify({ message: 'Report generated successfully', color: 'positive', icon: 'check' }); await fetchRecentReports(); downloadReport(response.data); } catch (error) { $q.notify({ message: error.message, color: 'negative', icon: 'error' }); } finally { generating.value = false; } }; const viewReport = (id) => { $q.notify({ message: 'Report viewer coming soon', color: 'info' }); }; const downloadReport = (report) => { $q.notify({ message: `Downloading ${report.type} report...`, color: 'info' }); }; onMounted(() => { const today = new Date(); const firstDay = new Date(today.getFullYear(), today.getMonth(), 1); dateTo.value = today.toISOString().split('T')[0]; dateFrom.value = firstDay.toISOString().split('T')[0]; fetchRecentReports(); }); return { loading, generating, recentReports, reportType, reportTypes, dateFrom, dateTo, columns, generateReport, viewReport, downloadReport }; } });
</script>
<style lang="scss" scoped>
.stat-card { transition: all 0.2s; &:hover { transform: translateY(-4px); box-shadow: 0 8px 16px rgba(0,0,0,0.15); } }
</style>
