<template>
  <q-page padding>
    <div class="q-pa-md" style="max-width: 1000px; margin: 0 auto;">
      <h5 class="q-my-none q-mb-md">{{ $t('nav.settings') }}</h5>
      <q-tabs v-model="tab" align="left" class="q-mb-md"><q-tab name="general" label="General" icon="settings" /><q-tab name="notifications" label="Notifications" icon="notifications" /><q-tab name="integrations" label="Integrations" icon="extension" /><q-tab name="users" label="Users" icon="people" /></q-tabs>
      <q-tab-panels v-model="tab" animated>
        <q-tab-panel name="general"><q-card><q-card-section><div class="text-h6 q-mb-md">General Settings</div><q-form @submit="saveSettings" class="q-gutter-md"><q-input v-model="settings.companyName" label="Company Name" outlined /><q-input v-model="settings.companyEmail" label="Company Email" type="email" outlined /><q-input v-model="settings.companyPhone" label="Company Phone" outlined /><q-select v-model="settings.defaultCurrency" :options="['EUR', 'USD', 'RUB', 'BGN']" label="Default Currency" outlined /><q-select v-model="settings.defaultLanguage" :options="['en', 'ru', 'bg']" label="Default Language" outlined /><q-select v-model="settings.timezone" :options="['Europe/Moscow', 'Europe/Sofia', 'Europe/Berlin']" label="Timezone" outlined /><div class="row justify-end"><q-btn type="submit" label="Save Changes" color="primary" :loading="saving" no-caps unelevated /></div></q-form></q-card-section></q-card></q-tab-panel>
        <q-tab-panel name="notifications"><q-card><q-card-section><div class="text-h6 q-mb-md">Notification Settings</div><q-list><q-item tag="label"><q-item-section avatar><q-toggle v-model="notifications.email" color="primary" /></q-item-section><q-item-section><q-item-label>Email Notifications</q-item-label><q-item-label caption>Receive email notifications for important events</q-item-label></q-item-section></q-item><q-item tag="label"><q-item-section avatar><q-toggle v-model="notifications.telegram" color="primary" /></q-item-section><q-item-section><q-item-label>Telegram Notifications</q-item-label><q-item-label caption>Receive notifications via Telegram bot</q-item-label></q-item-section></q-item><q-item tag="label"><q-item-section avatar><q-toggle v-model="notifications.newTickets" color="primary" /></q-item-section><q-item-section><q-item-label>New Tickets</q-item-label><q-item-label caption>Notify about new support tickets</q-item-label></q-item-section></q-item><q-item tag="label"><q-item-section avatar><q-toggle v-model="notifications.payments" color="primary" /></q-item-section><q-item-section><q-item-label>Payments</q-item-label><q-item-label caption>Notify about payment activities</q-item-label></q-item-section></q-item></q-list><q-card-actions align="right"><q-btn label="Save Changes" color="primary" @click="saveNotifications" :loading="saving" no-caps unelevated /></q-card-actions></q-card-section></q-card></q-tab-panel>
        <q-tab-panel name="integrations"><q-card><q-card-section><div class="text-h6 q-mb-md">Integrations</div><q-list separator><q-item><q-item-section avatar><q-icon name="telegram" size="32px" color="primary" /></q-item-section><q-item-section><q-item-label>Telegram Bot</q-item-label><q-item-label caption>Connect Telegram bot for notifications</q-item-label></q-item-section><q-item-section side><q-badge color="positive" label="Connected" v-if="integrations.telegram" /><q-btn flat label="Connect" color="primary" v-else /></q-item-section></q-item><q-item><q-item-section avatar><q-icon name="payment" size="32px" color="secondary" /></q-item-section><q-item-section><q-item-label>Stripe Payments</q-item-label><q-item-label caption>Accept online payments via Stripe</q-item-label></q-item-section><q-item-section side><q-badge color="positive" label="Active" v-if="integrations.stripe" /><q-btn flat label="Setup" color="primary" v-else /></q-item-section></q-item><q-item><q-item-section avatar><q-icon name="email" size="32px" color="info" /></q-item-section><q-item-section><q-item-label>Email Service</q-item-label><q-item-label caption>SMTP configuration for emails</q-item-label></q-item-section><q-item-section side><q-btn flat label="Configure" color="primary" /></q-item-section></q-item></q-list></q-card-section></q-card></q-tab-panel>
        <q-tab-panel name="users"><q-card><q-card-section><div class="row items-center q-mb-md"><div class="col"><div class="text-h6">User Management</div></div><div class="col-auto"><q-btn color="primary" icon="add" label="Add User" @click="showUserDialog = true" no-caps unelevated /></div></div><q-table :rows="users" :columns="userColumns" row-key="id" flat bordered><template v-slot:body-cell-role="props"><q-td :props="props"><q-badge color="primary" :label="props.row.role" /></q-td></template><template v-slot:body-cell-actions="props"><q-td :props="props"><q-btn flat round dense icon="edit" color="secondary" /><q-btn flat round dense icon="delete" color="negative" /></q-td></template></q-table></q-card-section></q-card></q-tab-panel>
      </q-tab-panels>
    </div>
  </q-page>
</template>
<script>
import { defineComponent, ref, onMounted, computed } from 'vue'; import { useQuasar } from 'quasar'; import { settingsAPI } from '../../api';
export default defineComponent({ name: 'SettingsPage', setup() { const $q = useQuasar(); const saving = ref(false), tab = ref('general'), showUserDialog = ref(false); const settings = ref({ companyName: 'ServAI', companyEmail: 'info@servai.com', companyPhone: '+7 (495) 123-4567', defaultCurrency: 'EUR', defaultLanguage: 'ru', timezone: 'Europe/Moscow' }); const notifications = ref({ email: true, telegram: true, newTickets: true, payments: true }); const integrations = ref({ telegram: true, stripe: true, email: false }); const users = ref([]); const userColumns = computed(() => [{ name: 'name', label: 'Name', field: 'name', align: 'left' }, { name: 'email', label: 'Email', field: 'email', align: 'left' }, { name: 'role', label: 'Role', field: 'role', align: 'center' }, { name: 'lastActive', label: 'Last Active', field: 'lastActive', align: 'left', format: val => new Date(val).toLocaleDateString() }, { name: 'actions', label: 'Actions', field: 'actions', align: 'center' }]); const fetchSettings = async () => { try { const response = await settingsAPI.get(); settings.value = response.data.general || settings.value; notifications.value = response.data.notifications || notifications.value; integrations.value = response.data.integrations || integrations.value; users.value = response.data.users || []; } catch (error) { console.error('Failed to load settings', error); } }; const saveSettings = async () => { saving.value = true; try { await settingsAPI.update({ general: settings.value }); $q.notify({ message: 'Settings saved successfully', color: 'positive', icon: 'check' }); } catch (error) { $q.notify({ message: error.message, color: 'negative', icon: 'error' }); } finally { saving.value = false; } }; const saveNotifications = async () => { saving.value = true; try { await settingsAPI.update({ notifications: notifications.value }); $q.notify({ message: 'Notification settings saved', color: 'positive', icon: 'check' }); } catch (error) { $q.notify({ message: error.message, color: 'negative', icon: 'error' }); } finally { saving.value = false; } }; onMounted(() => { fetchSettings(); }); return { saving, tab, showUserDialog, settings, notifications, integrations, users, userColumns, saveSettings, saveNotifications }; } });
</script>
